### ISSUE TITLE
Comparison to google-java-format

### ISSUE THREAD

**Issue by azdanov** [thorbenvh8/prettier-java#29]
I'm wondering how does `prettier-java` compare to [google-java-format](https://github.com/google/google-java-format)?

And what style guide is `prettier-java` adhering to?

**Comment by thorbenvh8** [comment]
Hi,
well its based on Javascript so it can run in the browser, thats maybe the only difference. It can be used in a javascript environment, which in some environments/usecases makes sense.

**Comment by Slooz** [comment]
I hate to bump this, but is that the only reason to use prettier-java over google-java-format? I use Prettier for other languages, and I'm evaluating whether my team should use Prettier for Java. google-java-format is more standard and popular, so I'm not really sure why we would or should use prettier-java. I'm not trying to hate on this project, because I love Prettier in general, but how would I convince my team/organization to use prettier-java over google-java-format? What are the advantages of using prettier-java?

I think it'd be valuable and helpful if this was talked about or documented somewhere.

**Comment by jhaber** [comment]
I like the simplicity of just being able to run prettier on everything, leveraging its plugin system to support additional languages like Java. google-java-format and prettier-java also diverge pretty strongly on their formatting choices, so you might want to format some example code through both to get a sense of the differences (if you're already using prettier for Javascript, the prettier-java output should look very natural, while the google-java-format will look quite jarring).

Java IDE support and tooling for google-java-format is generally better, but prettier is getting better support in IDEs like IntelliJ (and prettier-java should inherit these benefits, as a prettier plugin). google-java-format is more actively maintained, which historically didn't matter much given the glacial pace of Java syntax changes, however that pace has accelerated recently, so it's something to think about.
